./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEGL1SingleEGOrFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEG32L1SingleEGOrEtFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightClusterShapeFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightHEFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightEcalIsoFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightHcalIsoFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightPixelMatchFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightPMS2Filter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightGsfOneOEMinusOneOPFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightGsfMissingHitsFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightGsfDetaFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightGsfDphiFilter
./plot filterEff_TT_PU30to80_efficiency_tightid_nominal.root TT_PU30to80 hltEle32WPTightGsfTrackIsoFilter


./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEGL1SingleEGOrFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEG32L1SingleEGOrEtFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightClusterShapeFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightHEFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightEcalIsoFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightHcalIsoFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightPixelMatchFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightPMS2Filter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightGsfOneOEMinusOneOPFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightGsfMissingHitsFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightGsfDetaFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightGsfDphiFilter
./plot filterEff_TT_PU20to70_efficiency_tightid_nominal.root TT_PU20to70 hltEle32WPTightGsfTrackIsoFilter


./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEGL1SingleEGOrFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEG32L1SingleEGOrEtFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightClusterShapeFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightHEFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightEcalIsoFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightHcalIsoFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightPixelMatchFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightPMS2Filter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightGsfOneOEMinusOneOPFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightGsfMissingHitsFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightGsfDetaFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightGsfDphiFilter
./plot filterEff_QCD_efficiency_tightid_nominal.root QCD hltEle32WPTightGsfTrackIsoFilter


./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEGL1SingleEGOrFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEG32L1SingleEGOrEtFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightClusterShapeFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightHEFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightEcalIsoFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightHcalIsoFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightPixelMatchFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightPMS2Filter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightGsfOneOEMinusOneOPFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightGsfMissingHitsFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightGsfDetaFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightGsfDphiFilter
./plot filterEff_ZPrime_efficiency_tightid_nominal.root ZPrime hltEle32WPTightGsfTrackIsoFilter


./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEGL1SingleEGOrFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEG32L1SingleEGOrEtFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightClusterShapeFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightHEFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightEcalIsoFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightHcalIsoFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightPixelMatchFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightPMS2Filter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightGsfOneOEMinusOneOPFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightGsfMissingHitsFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightGsfDetaFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightGsfDphiFilter
./plot filterEff_ZtoEE_PU20to70_efficiency_tightid_nominal.root ZtoEE_PU20to70 hltEle32WPTightGsfTrackIsoFilter


./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEGL1SingleEGOrFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEG32L1SingleEGOrEtFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightClusterShapeFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightHEFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightEcalIsoFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightHcalIsoFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightPixelMatchFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightPMS2Filter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightGsfOneOEMinusOneOPFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightGsfMissingHitsFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightGsfDetaFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightGsfDphiFilter
./plot filterEff_ZtoEE_NoPU_efficiency_tightid_nominal.root ZtoEE_NoPU hltEle32WPTightGsfTrackIsoFilter
